import screeninfo,pygame
from pygame import Vector2,Rect

# WINDOW SIZES
SIZES = None

monitors = screeninfo.get_monitors()
for monitor in monitors:
    SIZES = (monitor.width,monitor.height)
    
TEST_SIZES = None
if TEST_SIZES:
    SIZES = TEST_SIZES

W,H = SIZES

# COLORS

BG_COL = (15,15,15)
GRID_COL = (50,50,50)

# PYGAMEUI SETTINGS

PYGAMEUI_SETTINGS = [
    {
        "element_ids":["menu_title"],
        "settings":{
            "font_size":50
        }
    },
    {
        "element_ids":["selected"],
        "settings":{
            "text_alignment":"left"
        }
    }
]

# CONSTANTS

DATA_FILE = "projects/"
DOTJSON = ".json"
GRID_SIZE = 0.5
HIDDEN_FLAG = " (hidden)"

# MENU

PROJECTS_NAMES_FILE = DATA_FILE+"projects"+DOTJSON

MSPACING = 10
MSS = 5
PLT = H/10
PROJECT_LIST_RECT = Rect(W/6,PLT,W/4,H-PLT-PLT/2)
MENU_TITLE_RECT = Rect(0,0,PROJECT_LIST_RECT.w,60)
MENU_TITLE_RECT.center = (PROJECT_LIST_RECT.centerx,PROJECT_LIST_RECT.top-45)
M_BTNW = 150
M_BTNH = 40
M_LABELW = 100
M_LABELH = 30
M_CREATEBTN_RECT = Rect(W/2,H/2-150,M_BTNW,M_BTNH)
M_OPENBTN_RECT = Rect(W/2,H/2-150+M_BTNH+MSPACING,M_BTNW,M_BTNH)
M_DELETEBTN_RECT = Rect(W/2,H/2+M_BTNH/2,M_BTNW,M_BTNH)
M_QUITBTN_RECT = Rect(W/2,H/2+150,M_BTNW-50,M_BTNH)

MWINW = int(W/4.5)
MWINH = H/4
MWINHALF = MWINW/2-100
MWINENTRYW = M_BTNW+100
M_NEWPROJECT_WIN_RECT = Rect(W/2-MWINW/2,H/2-MWINH/2,MWINW,MWINH)
MWIN_NAMELABEL_RECT = Rect(MWINHALF-MSPACING/2-M_LABELW,MSS+5,M_LABELW,M_LABELH)
MWIN_NAMENTRY_RECT = Rect(MWINHALF,MSPACING,MWINENTRYW,M_BTNH)
MWIN_TILESIZELABEL_RECT  = Rect(MWINHALF-MSPACING/2-M_LABELW,MSS*2+5*2+M_BTNH,M_LABELW,M_LABELH)
MWIN_TILESIZEENTRY_RECT = Rect(MWINHALF,MSPACING*2+M_BTNH,MWINENTRYW,M_BTNH)
MWIN_MAPSIZELABEL_RECT = Rect(MWINHALF-MSPACING/2-M_LABELW,MSS*3+5*3+M_BTNH*2,M_LABELW,M_LABELH)
MWIN_MAPSIZEENTRYX_RECT = Rect(MWINHALF,MSPACING*3+M_BTNH*2,MWINENTRYW/2-MSPACING/2,M_BTNH)
MWIN_MAPSIZEWNTRYY_RECT = Rect(MWINHALF+MWINENTRYW/2-MSPACING/2+MSPACING,MSPACING*3+M_BTNH*2,MWINENTRYW/2-MSPACING/2,M_BTNH)
MWIN_CANCELBTN_RECT = Rect(MWINW/2-MSPACING-(M_BTNW-50),MWINH-M_BTNH*2,M_BTNW-50,M_BTNH)
MWIN_CREATEBTN_RECT = Rect(MWINW/2,MWINH-M_BTNH*2,M_BTNW-50,M_BTNH)

# EDITOR

BTNW = 150
BTNWS = 100
BTNH = 30
TBO = 5
S = 5
BS = 10
IMGCONTH = 50
IMGSIZE = 40
TOPBAR_RECT = Rect(0,0,W,BTNH+10)

SCENE_VIEW_RECT = Rect(W/5,TOPBAR_RECT.bottom,W-W/5,H-M_BTNH+M_BTNH+20)
SCENE_VIEW_CENTER = Vector2(SCENE_VIEW_RECT.w/2,SCENE_VIEW_RECT.h/2)
SCENE_VIEW_POS = Vector2(SCENE_VIEW_RECT.x,SCENE_VIEW_RECT.y)
TILE_CHECK_RECT = Rect(0,0,SCENE_VIEW_RECT.w,SCENE_VIEW_RECT.h)

QUITBTN_RECT = Rect(W-S-BTNWS,TBO,BTNWS,BTNH)
SAVEQUITBTN_RECT = Rect(W-S*2-BTNWS-BTNW,TBO,BTNW,BTNH)
MENUBTN_RECT = Rect(S,TBO,BTNW,BTNH)
SAVEBTN_RECT = Rect(S*2+BTNW,TBO,BTNW,BTNH)
EXPORTDROPDOWN_RECT = Rect(S*3+BTNW*2,TBO,BTNW,BTNH)
W1,W2,W3,W4 = 150,70,70,70
LEFTCONT_RECT = Rect(0,TOPBAR_RECT.bottom,W-SCENE_VIEW_RECT.w,H-TOPBAR_RECT.h)
THATW = (LEFTCONT_RECT.w/3)*2
OTHERW = (LEFTCONT_RECT.w-THATW)-S*3
LAYERLIST_RECT = Rect(S,IMGCONTH,LEFTCONT_RECT.w-S*2,LEFTCONT_RECT.h/2-100)

LAYERBTNS_RECTS = {
    "visibility":Rect(S,S,IMGSIZE,IMGSIZE),
    "up":Rect(S*2+IMGSIZE,S,IMGSIZE,IMGSIZE),
    "down":Rect(S*3+IMGSIZE*2,S,IMGSIZE,IMGSIZE),
    "save":Rect(S*4+IMGSIZE*3,S,IMGSIZE,IMGSIZE),
    "delete":Rect(S*5+IMGSIZE*4,S,IMGSIZE,IMGSIZE),
    "plus":Rect(LEFTCONT_RECT.w-S-IMGSIZE,S,IMGSIZE,IMGSIZE)
}

LILCW = 200
LILCONT_RECT = Rect(W-LILCW,SCENE_VIEW_RECT.y,LILCW,150)
SELECTEDLAYERLABEL_RECT = Rect(W-LILCW+S,SCENE_VIEW_RECT.y,500,40)
MODESELECTEDLABEL_RECT = Rect(W-LILCW+S,SCENE_VIEW_RECT.y+BTNH+S,500,40)
SELECTEDLABEL_RECT = Rect(W-LILCW+S,SCENE_VIEW_RECT.y+BTNH*2+S*2,500,40)
SELECTEDTOOLLABEL_RECT = Rect(W-LILCW+S,SCENE_VIEW_RECT.y+BTNH*3+S*3,500,40)

TCRW = IMGSIZE*3+S*4
TOOLSCONT_RECT = Rect(W/2-TCRW/2,SCENE_VIEW_POS.y,TCRW,IMGCONTH)
TOOLIMAGES_RECTS = {
    "paint":Rect(S,S,IMGSIZE,IMGSIZE),
    "erase":Rect(IMGSIZE+S*2,S,IMGSIZE,IMGSIZE),
    "move":Rect(IMGSIZE*2+S*3,S,IMGSIZE,IMGSIZE)
}

CREATELAYERENTRY_RECT = Rect(LEFTCONT_RECT.right,SCENE_VIEW_POS.y+S,THATW,BTNH)
CREATELAYERBTN_RECT = Rect(LEFTCONT_RECT.right+S+THATW,SCENE_VIEW_POS.y+S,OTHERW,BTNH)

TILESBTN_RECT = Rect(S,LAYERLIST_RECT.bottom+S,LEFTCONT_RECT.w/2-S*2-BTNH/2,BTNH)
OBJSBTN_RECT = Rect(S*2+TILESBTN_RECT.w,LAYERLIST_RECT.bottom+S,LEFTCONT_RECT.w/2-S*2-BTNH/2,BTNH)
ADDIMAGEIMG_RECT = Rect(LEFTCONT_RECT.w-S-BTNH,LAYERLIST_RECT.bottom+S,BTNH,BTNH)

ADDIMAGEENTRY_RECT = Rect(LEFTCONT_RECT.right,TILESBTN_RECT.y+LEFTCONT_RECT.y,THATW,BTNH)
ADDIMAGEBTN_RECT = Rect(LEFTCONT_RECT.right+S+THATW,TILESBTN_RECT.y+LEFTCONT_RECT.y,OTHERW,BTNH)

TILESCONT_RECT = Rect(S,TILESBTN_RECT.bottom+S,LEFTCONT_RECT.w-S*2,LEFTCONT_RECT.h-(TILESBTN_RECT.bottom+S*2))
OBJSCONT_RECT = Rect(S,TILESBTN_RECT.bottom+S,LEFTCONT_RECT.w-S*2,LEFTCONT_RECT.h-(TILESBTN_RECT.bottom+S*2))
IMAGE_SIZES = Vector2(50,50)
MAXIMGS = int(TILESCONT_RECT.w/IMAGE_SIZES.x)-1
TILESCONTSCROLLBAR_RECT = Rect(TILESCONT_RECT.w-24,0,24,TILESCONT_RECT.h)
OBJSCONTSCROLLBAR_RECT = Rect(OBJSCONT_RECT.w-24,0,24,OBJSCONT_RECT.h)